sudo: required
services:
  - docker

before_install:
  - docker build -t valvarezxxx/docker-react -f Dockerfile.dev .

script:
  - docker run valvarezxxx/docker-react npm run ci_test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerrepaso"
  env: "Dockerrepaso-env"
  bucket_name: "elasticbeanstalk-us-east-1-223488973913"
  bucket_path: "dockerrepaso"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
